---
development:
  cloud_name: bste-tamu
  api_key: '694276974795492'
  api_secret: tVqFIwFjo2qyE6cDDxzzFyxBLwE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: bste-tamu
  api_key: '694276974795492'
  api_secret: tVqFIwFjo2qyE6cDDxzzFyxBLwE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: bste-tamu
  api_key: '694276974795492'
  api_secret: tVqFIwFjo2qyE6cDDxzzFyxBLwE
  enhance_image_tag: true
  static_image_support: false
